/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "calculator.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

struct CALCULATOR *
calculator_proc_1(struct CALCULATOR *argp, CLIENT *clnt)
{
	static struct CALCULATOR clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, CALCULATOR_PROC,
		(xdrproc_t) xdr_CALCULATOR, (caddr_t) argp,
		(xdrproc_t) xdr_CALCULATOR, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
